### ISSUE TITLE
expiration time for questions

### ISSUE THREAD

**Issue by NARKOZ** [viode/viode#12]
auto close questions based on a date

**Comment by colinwahl** [comment]
How long are you thinking we let questions stay up? Or should we have the admin set that somewhere?

**Comment by rhuberdeau** [comment]
Is the expiration for unanswered questions or all questions?

**Comment by NARKOZ** [comment]
Here is how I see it: after a period (30 days by default) question gets closed and users can't add answers to that question anymore.

@rhuberdeau all questions.

**Comment by samnang** [comment]
@NARKOZ what's purpose to expire questions? What I am wondering when questions become expired, then people will ask new questions that will be similar or the same again to get answers, do we want to see those duplicated questions?
