### ISSUE TITLE
login via social profiles

### ISSUE THREAD

**Issue by NARKOZ** [viode/viode#6]

**Comment by samnang** [comment]
I suppose we want to only support for twitter & facebook?

**Comment by dantesolis** [comment]
What about github?

**Comment by dantesolis** [comment]
If this needs to still be implemented, I can go ahead and do it if you guys like.

**Comment by NARKOZ** [comment]
Let's start with facebook and twitter. We can add other providers later on.

@dantesolis Sure, feel free to send a PR and we'll take a look. Thanks!

**Comment by dantesolis** [comment]
Cool, I'll get to work and send a pull request. 

Cheers,

**Comment by Leoxxid** [comment]
I gonna do this!
