### ISSUE TITLE
asking questions to specific users

### ISSUE THREAD

**Issue by NARKOZ** [viode/viode#7]

**Comment by rhuberdeau** [comment]
Would we want a separate field in the form to indicate who is getting asked? Or would we want to support @username somehow ( maybe in the title field )? 

If the question is directed to a specific user would we want other users to still be able to answer it? 
Would we want to send that user some sort of notification that someone asked them a question? If yes, would it be on login, email, both?

**Comment by NARKOZ** [comment]
> Would we want a separate field in the form to indicate who is getting asked? Or would we want to support @username somehow ( maybe in the title field )?

We need a field in the new question form. We also need to add 'Ask this user' button to users profiles.


>If the question is directed to a specific user would we want other users to still be able to answer it?

Yes, others still should be able to answer.

 
>Would we want to send that user some sort of notification that someone asked them a question? If yes, would it be on login, email, both?

Let's notify the user via email until we come up with notification system.

**Comment by rhuberdeau** [comment]
I got sidetracked until recently. I'm almost finished with this- just working on sending the email asynchronously via ActiveMailer, ActiveJob and Sidekiq.
